=== folio-org/mod-reporting/ramls/updates-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "LDP table-and-schema pairs with last-update information",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "tableName": {
        "type": "string",
        "description": "The name of a table within an LDP schema"
      },
      "tableSchema": {
        "type": "string",
        "description": "The name of the LDP schema containing the table"
      },
      "lastUpdate": {
        "type": "string",
        "description": "ISO-8601 timestamp of last update to the table"
      },
      "elapsedRealTime": {
        "type": "number",
        "description": "The number of seconds elapsed since the last update"
      }
    },
    "additionalProperties": false,
    "required": [
      "tableName",
      "tableSchema",
      "lastUpdate",
      "elapsedRealTime"
    ]
  }
}

=== folio-org/mod-reporting/ramls/examples/updates-example.json
[
  {
    "tableSchema": "folio_derived",
    "tableName": "agreements_package_content_item",
    "lastUpdate": "2025-01-24 00:59:48.421449+00",
    "elapsedRealTime": 0.0452
  },
  {
    "tableSchema": "folio_derived",
    "tableName": "feesfines_accounts_actions",
    "lastUpdate": "2025-01-24 00:59:48.909772+00",
    "elapsedRealTime": 0.0526
  }
]
